### ISSUE TITLE
Certificate error upon visiting ihp-forum.digitallyinduced.com

### ISSUE THREAD

**Issue by themmes** [digitallyinduced/ihp-forum#7]
Receiving 

```
NET::ERR_CERT_COMMON_NAME_INVALID 
Subject: *.ihpapp.com
```

**Comment by Laobiz** [comment]
Hey @themmes,
as IHP-Forum is now hosted on ihp-cloud we redirect the domain ihp-forum.digitallyinduced.com to forum.ihpapp.com .
I attached the wrong certificate to the vhost but now it should work properly. Can you test it again?

**Comment by themmes** [comment]
🎉 Works perfectly now!
